### ISSUE TITLE
Fix job submission

### ISSUE THREAD

**Issue by yannick-fischer31** [uhh-cms/DiJetJERC#28]
Submitting Jobs to htcondor is not possible at the moment. The analysis run only locally. When trying to submit, multiple Error such as` AttributeError: module 'setuptools' has no attribute 'extern'` According to Mathis this is most likely due to the outdated Columnflow version.

**Comment by mschrode** [comment]
Thanks @yannick-fischer31 for starting to test and for posting here any issues you are encountering!
